azure:
  branches:
    daily-update:
      pull_credentials:
        password: xDHBncnAPPXcsodP6AqAo8kEDxNoOR5X8r5krtaZp++ACRAwcL6j
        username: thirdaiplatform-pull-daily-update
      push_credentials:
        password: Kl0pYEl2c2iEJfK6rIo/fI3Vva1KOmhxd+cDwQtZTb+ACRDxWxvv
        username: thirdaiplatform-push-daily-update
      version: 0.0.1
    docker_tests:
      pull_credentials:
        password: ojqTob8LipMFHD5CUtYQqKFT4Yj0dgA42fpzKm08Uu+ACRB3D2G8
        username: thirdaiplatform-pull-docker-tests
      push_credentials:
        password: F2yp3m5uWE/8liQ6lFyGTtZxlMgpirMRStAcdQc6Mu+ACRB6nTfH
        username: thirdaiplatform-push-docker-tests
      version: 0.0.1
    local_registry:
      pull_credentials:
        password: 1N7CsVddLTv4+enVywVCgjOkDkMqpv63WenU0bWihF+ACRBVBnXz
        username: thirdaiplatform-pull-local-registry
      push_credentials:
        password: rt/BPKK778qUWXa3YZjHUTNsVc9MkwU53kydXmSscF+ACRAfiMQq
        username: thirdaiplatform-push-local-registry
    mshift:
      pull_credentials:
        password: uGpzj1Ylkgc+PBbQ5e3r1nEFC+BtiQK2cNeFdRW1NP+ACRCsrcq2
        username: thirdaiplatform-pull-mshift
      push_credentials:
        password: 6DSwbtoUZpFEsAEdV6bL9VpVK+8qJoRcn8li7VRgAz+ACRDNRKRx
        username: thirdaiplatform-push-mshift
      version: 0.0.12
    node-discovery:
      pull_credentials:
        password: axmgUWuDvRlAMdEnB8xydKqFEtrAGtm2WuOWEU0KEb+ACRBKSjGY
        username: thirdaiplatform-pull-node-discovery
      push_credentials:
        password: OftsSULdLXe5IQU+V1hA1BXMp5oMWHsqZBH+rfMrHj+ACRCMZPg/
        username: thirdaiplatform-push-node-discovery
      version: 0.0.1
    on-prem-llm:
      pull_credentials:
        password: lZit7mOLUB2e7j/Ak50OXCHer4EdaCUDZ8EVHbQnJj+ACRAP/xev
        username: thirdaiplatform-pull-on-prem-llm
      push_credentials:
        password: /6WCAtZuvdhWPyw2VTArrXEgaxOf/5J0NJHoXfflGX+ACRAcpvWw
        username: thirdaiplatform-push-on-prem-llm
      version: 0.0.6
    release-test:
      pull_credentials:
        password: ivG00o0TTx10TZDh6Y4chVxDEGR92h0ib4uA5WjF2H+ACRC95ggs
        username: thirdaiplatform-pull-release-test
      push_credentials:
        password: c3P3qKGzI2dBE6fiKJfF+zHos70aRFcJ6vVLZh+zq0+ACRCEzI7T
        username: thirdaiplatform-push-release-test
      version: 0.0.18
    release-test-main:
      pull_credentials:
        password: 5Di/+qW2Q/++3mp0Ah/rkCq33n2N7f0E8G4+cSHnub+ACRClJvCj
        username: thirdaiplatform-pull-release-test-main
      push_credentials:
        password: y/iKY+7IwCrcdd61Rp3vma3gTyYScI72TY7484cJ6c+ACRBkPJv/
        username: thirdaiplatform-push-release-test-main
      version: 0.0.29
    test_1:
      pull_credentials:
        password: lfhxcL/qmrYP24rIH2vmRNSYV9ZlNCfxJyQI6E3kVi+ACRDjUz22
        username: thirdaiplatform-pull-test-1
      push_credentials:
        password: XCM9NnRa3ybEjKNbsZSl8eEio1VC3NHMOGCwqOXb/r+ACRCD4kbn
        username: thirdaiplatform-push-test-1
      version: 0.0.1
    test_2:
      pull_credentials:
        password: wgAJy1o7t1aybREkWMi8oQnsHxLg5eetcD98yyXpXY+ACRB5rap/
        username: thirdaiplatform-pull-test-2
      push_credentials:
        password: v5yOJruG8kxPB5jpr50OurWDYBRuc+lw+VmXV+p4QU+ACRBitPEC
        username: thirdaiplatform-push-test-2
      version: 0.0.2
    test_3:
      pull_credentials:
        password: /5bqfPyF2QlEKJ/Xo26ctZmZ7SAqYNaq6P+DVRaMI2+ACRCxY8ds
        username: thirdaiplatform-pull-test-3
      push_credentials:
        password: PkCR7YWr0zG/sW6rZex19qzQdR4A1QNg7RXWFKCBGt+ACRDolvsb
        username: thirdaiplatform-push-test-3
      version: 0.0.1
  registry: thirdaiplatform.azurecr.io
provider: azure
